version: "3.7"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INIT_DB_ROOT_USERNAME=admin_user
      - MONGO_INIT_DB_ROOT_PASSWORD=admin_pass
      - MONGO_INIT_DB_DATABASE=database
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
